# Generated by Django 3.0.1 on 2020-03-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_blogcricket_blognba_blogtennis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSerieA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLaLiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogEPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogChampionsLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Blog')),
            ],
        ),
    ]
